[package]
name = "rust_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.6.4"
dotenv = "0.15.0"
sqlx = { version = "0.7", features = [ "runtime-async-std-native-tls", "postgres" ] }